warn = [
    # rustc
    "unsafe_code",
    "missing_docs",
    # Restriction
    "clippy::clone_on_ref_ptr",
    "clippy::empty_structs_with_brackets",
    "clippy::get_unwrap",
    "clippy::mem_forget",
    "clippy::rc_buffer",
    "clippy::rc_mutex",
    "clippy::same_name_method",
    "clippy::string_to_string",
    "clippy::unnecessary_self_imports",
    "clippy::verbose_file_reads",
    # Cargo
    "clippy::cargo_common_metadata",
    "clippy::multiple_crate_versions",
    "clippy::wildcard_dependencies",
    # Pedantic
    "clippy::cast_lossless",
    "clippy::cast_possible_truncation",
    "clippy::cast_possible_wrap",
    "clippy::cast_sign_loss",
    "clippy::enum_glob_use",
    "clippy::expl_impl_clone_on_copy",
    "clippy::explicit_into_iter_loop",
    "clippy::explicit_iter_loop",
    "clippy::fn_params_excessive_bools",
    "clippy::if_not_else",
    "clippy::implicit_clone",
    "clippy::implicit_saturating_sub",
    "clippy::large_stack_arrays",
    "clippy::large_types_passed_by_value",
    "clippy::manual_ok_or",
    "clippy::map_unwrap_or",
    "clippy::mut_mut",
    "clippy::needless_bitwise_bool",
    "clippy::needless_continue",
    "clippy::range_plus_one",
    "clippy::ref_binding_to_reference",
    "clippy::ref_option_ref",
    "clippy::unnecessary_join",
    "clippy::verbose_bit_mask",
]
